# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# You can specify a custom docker image from Docker Hub as your build environment.
# ----------------------
# Configuration to run automate tests
# saba.wasim@elucidata.io
# ----------------------
# ---Valid only for this branch : pipeline_test--
          

image: valtechcanada/python-postgres

pipelines:
  default:
    - step:
        script: 
          - echo "Pipelines run only on develop branch"
          
  branches:
    CI:
      - step:
         script:
            - echo "BUILD IMAGE SUCESSFULLY DONE"
            - echo "PIPELINE STARTED ..........."
            - echo "CORNA PACKAGE IS BEING INSTALLED FROM REPO"
            - python -m pip install --upgrade pip
            - sudo apt-get update
            - sudo apt-get -y install libatlas-base-dev gfortran
            - pip install -r requirements.txt
            - python setup.py install
            - echo "CORNA PACKAGE INSTALLED SUCESSFULLY"
            - echo "STARTING TESTING........"
            - pip install pytest-cov
            - echo "CALCULATING TEST COVERAGE ..........."
            - python -m py.test --cov=./ --cov-config .coveragerc  tests/
            - echo "TEST COVERAGE REPORT SHOWING ABOVE"
            - echo "PIPELINE SUCESSFULLY COMPLETED"